///////////////////////////////////////////////////////////////////////////////
// Untitled1Services.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Untitled1 = 0x3F000000;
#define SRVNAME_UNTITLED1 "Untitled1"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_Untitled1CModule1 = {0x5c7e6bb4,0x01d9,0x4c18,{0xa2,0x00,0xf7,0x0e,0xe8,0x07,0x3f,0x60}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_Module1DefaultAdsPort = 0x00000001;
const PTCID PID_Module1Counter = 0x00000003;
const PTCID PID_Module1move = 0x00000004;
const PTCID PID_Module1target = 0x00000005;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
typedef struct _Module1Inputs
{
	USHORT status_word;
} Module1Inputs, *PModule1Inputs;

#pragma pack(push,1)
typedef struct _Module1Outputs
{
	USHORT control_word;
	LONG target;
	char mode;
	ULONG vel;
	ULONG acc;
	ULONG dec;
} Module1Outputs, *PModule1Outputs;
#pragma pack(pop)

///</AutoGeneratedContent>
typedef struct _Module1DataArea3
{
	INT state;
	LONG target_position;

} Module1DataArea3;


///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_Module1Inputs 0
#define ADI_Module1Outputs 1
#define ADI_Module1DataArea3 2
///</AutoGeneratedContent>

///<AutoGeneratedContent id="InterfaceIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="EventClasses">
///</AutoGeneratedContent>
